# Generated by Django 4.2 on 2025-09-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tryitle',
            new_name='title',
        ),
    ]
